[package]
name = "persistence_windows"
version = "0.1.0"
edition = "2018"

[dependencies]
data_types = { path = "../data_types" }
internal_types = { path = "../internal_types" }
observability_deps = { path = "../observability_deps" }
snafu = "0.6.2"
time = { path = "../time" }

[dev-dependencies]
test_helpers = { path = "../test_helpers" }
