[package]
name = "querier"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-flight = "9.1"
async-trait = "0.1.42"
client_util = { path = "../client_util" }
futures = "0.3"
generated_types = { path = "../generated_types" }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
rand = "0.8.3"
thiserror = "1.0"
tokio = { version = "1.17", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.0" }
tonic = { version = "0.6" }
trace = { path = "../trace" }
workspace-hack = { path = "../workspace-hack"}
