[package]
name = "querier"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-flight = "9.1"
async-trait = "0.1.42"
backoff = { path = "../backoff" }
client_util = { path = "../client_util" }
futures = "0.3"
generated_types = { path = "../generated_types" }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
iox_object_store = { path = "../iox_object_store" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
rand = "0.8.3"
thiserror = "1.0"
time = { path = "../time" }
tokio = { version = "1.17", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.0" }
tonic = { version = "0.6" }
trace = { path = "../trace" }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
query = { path = "../query" }
