[package]
name = "querier"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "9.1"
arrow-flight = "9.1"
async-trait = "0.1.42"
backoff = { path = "../backoff" }
bytes = "1.0"
client_util = { path = "../client_util" }
data_types2 = { path = "../data_types2" }
datafusion = { path = "../datafusion" }
db = { path = "../db" }
futures = "0.3"
generated_types = { path = "../generated_types" }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
iox_object_store = { path = "../iox_object_store" }
job_registry = { path = "../job_registry" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
pin-project = "1.0"
predicate = { path = "../predicate" }
prost = "0.9"
query = { path = "../query" }
rand = "0.8.3"
schema = { path = "../schema" }
thiserror = "1.0"
time = { path = "../time" }
tokio = { version = "1.17", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.0" }
tonic = { version = "0.6" }
trace = { path = "../trace" }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
arrow = { version = "9.1", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
bytes = "1.0"
mutable_batch_lp = { path = "../mutable_batch_lp" }
