version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # https://github.com/tkaitchuck/aHash/issues/95
      dependency-name: "indexmap"
