[package]
name = "delorean"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
rand = "0.7.2"
integer-encoding = "1.0.7"

# actix 2.0 should release around 12/20
actix-rt = "1.0"
actix-web = "2.0"

dotenv = "0.10"
dirs = "2.0.2"
env_logger = "0.6"
failure = "0.1.1"
futures = "0.3.1"

serde_json = "1.0.44"
serde = "1.0"
csv = "1.1"
rocksdb = "0.13"
byteorder = "0.3"

num_cpus = "1.11.1"

# waiting for tonic to bump up to use newest tokio
#tonic = "0.1.0-alpha.6"
prost = "0.5.0"

# using croaring here because we needed Treemap support for u64
# for series ids and we needed serialization, which the pure Rust
# crate didn't offer.
croaring = "0.4.2"

[build-dependencies]
#tonic-build = "0.1.0-alpha.6"
prost-build = { version = "0.5.0" }

[dev-dependencies]
reqwest = { version = "0.10.1", features = ["blocking"] }
assert_cmd = "0.12.0"
