[workspace]
# In alphabetical order
members = [
    "arrow_util",
    "client_util",
    "data_types",
    "datafusion",
    "datafusion_util",
    "entry",
    "generated_types",
    "grpc-router",
    "grpc-router-test-gen",
    "influxdb2_client",
    "influxdb_iox",
    "influxdb_iox_client",
    "influxdb_line_protocol",
    "influxdb_storage_client",
    "influxdb_tsm",
    "internal_types",
    "iox_data_generator",
    "iox_object_store",
    "lifecycle",
    "logfmt",
    "metric",
    "metric_exporters",
    "mutable_batch",
    "mutable_batch_lp",
    "mutable_batch_pb",
    "mutable_buffer",
    "object_store",
    "observability_deps",
    "packers",
    "panic_logging",
    "parquet_catalog",
    "parquet_file",
    "persistence_windows",
    "predicate",
    "query",
    "query_tests",
    "read_buffer",
    "schema",
    "server",
    "server_benchmarks",
    "test_helpers",
    "time",
    "trace",
    "trace_exporters",
    "trace_http",
    "tracker",
    "trogging",
    "write_buffer",
]
default-members = ["influxdb_iox"]

exclude = [
    "*.md",
    "*.txt",
    ".circleci/",
    ".editorconfig",
    ".git*",
    ".github/",
    ".kodiak.toml",
    "Dockerfile*",
    "LICENSE*",
    "buf.yaml",
    "docker/",
    "docs/",
    "massif.out.*",
    "perf/",
    "scripts/",
    "test_fixtures/",
    "tools/",
]

[profile.release]
debug = true

[profile.bench]
debug = true
