[package]
name = "ingester2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow-flight = "27.0.0"
arrow_util = { version = "0.1.0", path = "../arrow_util" }
async-trait = "0.1.58"
backoff = { version = "0.1.0", path = "../backoff" }
bytes = "1.3.0"
data_types = { version = "0.1.0", path = "../data_types" }
datafusion.workspace = true
datafusion_util = { path = "../datafusion_util" }
dml = { version = "0.1.0", path = "../dml" }
flatbuffers = "22"
futures = "0.3.25"
generated_types = { version = "0.1.0", path = "../generated_types" }
hashbrown.workspace = true
iox_catalog = { version = "0.1.0", path = "../iox_catalog" }
iox_query = { version = "0.1.0", path = "../iox_query" }
iox_time = { path = "../iox_time" }
metric = { version = "0.1.0", path = "../metric" }
mutable_batch = { version = "0.1.0", path = "../mutable_batch" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
object_store = "0.5.1"
observability_deps = { version = "0.1.0", path = "../observability_deps" }
once_cell = "1.16.0"
parking_lot = "0.12.1"
pin-project = "1.0.12"
predicate = { version = "0.1.0", path = "../predicate" }
prost = { version = "0.11.2", default-features = false, features = ["std"] }
rand = "0.8.5"
schema = { version = "0.1.0", path = "../schema" }
service_grpc_catalog = { version = "0.1.0", path = "../service_grpc_catalog" }
thiserror = "1.0.37"
tokio = { version = "1.22", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tonic = "0.8.3"
trace = { version = "0.1.0", path = "../trace" }
uuid = "1.2.2"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
assert_matches = "1.5.0"
datafusion_util = { path = "../datafusion_util" }
lazy_static = "1.4.0"
mutable_batch_lp = { path = "../mutable_batch_lp" }
paste = "1.0.9"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
