[package]
name = "ioxd"
version = "0.1.0"
edition = "2021"


[dependencies]
# Workspace dependencies, in alphabetical order
clap_blocks = { path = "../clap_blocks" }
compactor = { path = "../compactor" }
data_types2 = { path = "../data_types2" }
dml = { path = "../dml" }
generated_types = { path = "../generated_types" }
ingester = { path = "../ingester" }
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
metric_exporters = { path = "../metric_exporters" }
mutable_batch = { path = "../mutable_batch" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
panic_logging = { path = "../panic_logging" }
query = { path = "../query" }
router = { path = "../router" }
router2 = { path = "../router2" }
server = { path = "../server" }
service_common = { path = "../service_common" }
service_grpc_flight = { path = "../service_grpc_flight" }
service_grpc_influxrpc = { path = "../service_grpc_influxrpc" }
service_grpc_testing = { path = "../service_grpc_testing" }
time = { path = "../time" }
trace = { path = "../trace" }
trace_exporters = { path = "../trace_exporters" }
trace_http = { path = "../trace_http" }
write_buffer = { path = "../write_buffer" }

# Crates.io dependencies, in alphabetical order
ansi_term = "0.12"
arrow-flight = "11"
async-trait = "0.1"
clap = { version = "3", features = ["derive", "env"] }
futures = "0.3"
hashbrown = "0.12"
http = "0.2.0"
hyper = "0.14"
num_cpus = "1.13.0"
pprof = { version = "0.7", default-features = false, features = ["flamegraph", "prost-codec"], optional = true }
snafu = "0.7"
thiserror = "1.0.30"
tokio = { version = "1.17", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.1" }
tonic = "0.6"
tonic-health = "0.5.0"
tonic-reflection = "0.3.0"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
# Workspace dependencies, in alphabetical order
arrow_util = { path = "../arrow_util" }
test_helpers = { path = "../test_helpers" }
iox_tests = { path = "../iox_tests" }

# Crates.io dependencies, in alphabetical order
assert_cmd = "2.0.2"
tempfile = "3.1.0"
