[package]
name = "sharder"
version = "0.1.0"
edition = "2021"

[dependencies]
data_types = { path = "../data_types" }
hashbrown = "0.12"
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
parking_lot = "0.12"
siphasher = "0.3"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
criterion = { version = "0.3.4", features = ["async_tokio", "html_reports"] }
rand = "0.8.3"

[[bench]]
name = "sharder"
harness = false
