[package]
name = "influxdb3_load_generator"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Core Crates
observability_deps.workspace = true
trogging.workspace = true

# Local Deps
influxdb3_client = { path = "../influxdb3_client" }
influxdb3_process = { path = "../influxdb3_process", default-features = false }

# crates.io Dependencies
anyhow.workspace = true
bytes.workspace = true
chrono.workspace = true
clap.workspace = true
csv.workspace = true
dotenvy.workspace = true
humantime.workspace = true
parking_lot.workspace = true
rand.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
tokio.workspace = true
thiserror.workspace = true
url.workspace = true

# compact test dependencies
clap_blocks.workspace = true
data_types.workspace = true
iox_query.workspace = true
parquet_file.workspace = true
schema.workspace = true

influxdb3_write = { path = "../influxdb3_write" }

arrow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
datafusion.workspace = true
datafusion_util.workspace = true
itertools.workspace = true
num_cpus.workspace = true
parquet.workspace = true
object_store.workspace = true
sha2.workspace = true

[lints]
workspace = true
