[package]
name = "ingester"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2021"

[dependencies]
iox_catalog = { path = "../iox_catalog" }
mutable_batch = { path = "../mutable_batch"}
parking_lot = "0.11.2"
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}
