[package]
name = "ingester"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2021"

[dependencies]
arrow = { version = "7.0", features = ["prettyprint"] }
snafu = "0.7"
iox_catalog = { path = "../iox_catalog" }
parking_lot = "0.11.2"