[package]
name = "parquet_file"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow_deps = { path = "../arrow_deps" }
bytes = "1.0"
data_types = { path = "../data_types" }
futures = "0.3.7"
generated_types = { path = "../generated_types" }
internal_types = {path = "../internal_types"}
object_store = {path = "../object_store"}
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.1"
prost = "0.7"
prost-types = "0.7"
query = { path = "../query" }
snafu = "0.6"
thrift = "0.13"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"
tracker = { path = "../tracker" }
uuid = { version = "0.8", features = ["serde", "v4"] }