[package]
name = "parquet_file"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow_deps = { path = "../arrow_deps" }
bytes = "1.0"
futures = "0.3.7"
object_store = {path = "../object_store"}
parking_lot = "0.11.1"
read_buffer = { path = "../read_buffer" }
snafu = "0.6"