[package]
name = "trace"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2018"
description = "Distributed tracing support within IOx"

[dependencies]

chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
http = "0.2.0"
http-body = "0.4"
itertools = "0.10"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11"
pin-project = "1.0"
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
snafu = "0.6"
tower = "0.4"

[dev-dependencies]
