[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
futures = "0.3.28"
hashbrown.workspace = true
metric = { version = "0.1.0", path = "../metric" }
prost = "0.11.9"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["net", "io-util", "time", "rt", "sync", "macros"] }
tracing = "0.1.37"
uuid = { version = "1.3.3", features = ["v4"] }

[build-dependencies]
prost-build = "0.11.9"

[dev-dependencies]
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
