[package]
name = "pbjson_build"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2018"
description = "Generates Serialize and Deserialize implementations for prost message types"

[dependencies]

heck = "0.3"
prost = "0.8"
prost-types = "0.8"
itertools = "0.10"

[dev-dependencies]
tempfile = "3.1"
pbjson_test = { path = "../pbjson_test" }