[package]
name = "query_tests2"
description = "Tests of the query engine against different database configurations"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.60"
dotenvy = "0.15.6"
ingester2 = { path = "../ingester2" }
iox_catalog = { path = "../iox_catalog" }
iox_query = { path = "../iox_query" }
generated_types = { path = "../generated_types" }
metric = { path = "../metric" }
object_store = "0.5.2"
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.17", features = ["parking_lot"] }
parquet_file = { path = "../parquet_file" }
snafu = "0.7"
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers" }
test_helpers_end_to_end = { path = "../test_helpers_end_to_end" }
tokio = { version = "1.22", features = ["macros", "parking_lot", "rt-multi-thread", "time"] }
workspace-hack = { path = "../workspace-hack"}
