[package]
name = "influxdb2_client"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies]
bytes = { version = "0.5.4", default-features = false }
futures = { version = "0.3.5", default-features = false }
reqwest = { version = "0.10.1", default-features = false, features = ["stream"] }
snafu = "0.6.6"
