name = "storage_cardinality_example"
base_seed = "this is a demo"

[[values]]
name = "role"
value = "storage"
cardinality = 1

[[values]]
name = "url"
value = "http://127.0.0.1:6060/metrics/usage"
cardinality = 1

[[values]]
name = "org"
# Fill in the value with the cardinality counter and 15 random alphanumeric characters
value = "{{id}}_{{random 15}}"
cardinality = 10000
has_one = ["env"]

[[values]]
name = "env"
value = "whatever-environment-{{id}}"
cardinality = 10

[[values]]
name = "bucket"
belongs_to = "org"
# each bucket will have a unique value so it can be used here to guarantee uniqueness even across orgs
value = "{{id}}_{{random 15}}"
# For each org, 3 buckets will be generated
cardinality = 3

[[values]]
name = "node_id"
value = "{{id}}"
cardinality = 100

[[values]]
name = "host"
value = "storage-{{node_id.value}}"
belongs_to = "node_id"
cardinality = 1

[[values]]
name = "partition_id"
value = "{{id}}"
cardinality = 10

# makes a tagset so every bucket exists on every node with every partition.
# So count(bucket) * count(node) * count(partition) cardinality.
[[tag_sets]]
name = "bucket_set"
for_each = [
    {value = "role", tag_key = "role"},
    {value = "url", tag_key = "url"},
    {value = "org", tag_key = "org_id"},
    {value = "org.env", tag_key = "env"},
    {value = "org.bucket", tag_key = "bucket_id"},
    {value = "node_id", tag_key = "node_id"},
    {value = "node_id", tag_key = "hostname"},
    {value = "node_id.host", tag_key = "host"},
    {value = "partition_id", tag_key = "partition_id"},
]

[[agents]]
name = "metric-scraper"
# sampling_interval = "1s"

[[agents.measurements]]
name = "storage_usage_bucket_cardinality"
# each unique tag set will get an entry in this measurement
# tag_set = "bucket_set"
#
#[[agents.measurements.tags]]
#name = "role"
#value = "storage"
#
#[[agents.measurements.tags]]
#name = "url"
#value = "http://127.0.0.1:6060/metrics/usage"

[[agents.measurements.fields]]
name = "gauge"
i64_range = [1, 8147240]
