[package]
name = "mutable_batch_pb"
version = "0.1.0"
edition = "2018"
description = "Conversion logic for binary write protocol <-> MutableBatch"

[dependencies]
generated_types = { path = "../generated_types" }
hashbrown = "0.11"
mutable_batch = { path = "../mutable_batch" }
schema = { path = "../schema" }
snafu = "0.6"

[dev-dependencies]
arrow_util = { path = "../arrow_util" }

