[package]
name = "wal"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1"
bytes = "1.2"
byteorder = "1.3.4"
crc32fast = "1.2.0"
data_types = { path = "../data_types" }
futures = "0.3"
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.4.0", features = ["parking_lot"] }
regex = "1.3.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
snafu = "0.7"
snap = "1.0.0"
tokio = { version = "1.21", features = ["macros", "fs", "io-util", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = "0.7"
uuid = "1.2"
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
dml = { path = "../dml" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
test_helpers = { path = "../test_helpers" }
