[package]
name = "wal"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1"
bytes = "1.4"
byteorder = "1.3.4"
crc32fast = "1.2.0"
data_types = { path = "../data_types" }
futures = "0.3"
generated_types = { path = "../generated_types" }
hashbrown.workspace = true
mutable_batch = { version = "0.1.0", path = "../mutable_batch" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.17", features = ["parking_lot"] }
parking_lot = "0.12"
prost = "0.11"
regex = "1.8.1"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.7"
snap = "1.0.0"
tokio = { version = "1.28", features = ["macros", "fs", "io-util", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = "0.7"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
dml = { path = "../dml" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
test_helpers = { path = "../test_helpers" }
