[package]
name = "parquet_to_line_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = { path = "../datafusion" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
futures = {version = "0.3"}
num_cpus = "1.13.1"
object_store = { version = "0.5.1" }
parquet_file  = { path = "../parquet_file" }
schema = { path = "../schema" }
tokio = "1.0"
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}


[dev-dependencies]
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
