[package]
name = "arrow_util"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"
description = "Apache Arrow utilities"

[dependencies]
ahash = "0.7.5"
arrow = { version = "6.0", features = ["prettyprint"] }
# used by arrow anyway (needed for printing workaround)
chrono = "0.4"
comfy-table = { version = "5.0", default-features = false }
hashbrown = "0.11"
num-traits = "0.2"
snafu = "0.6"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
rand = "0.8.3"
