[package]
name = "clap_blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_types = { path = "../data_types" }
iox_catalog = { path = "../iox_catalog" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
serving_readiness = { path = "../serving_readiness" }
trace_exporters = { path = "../trace_exporters" }
trace = { path = "../trace" }
time = { path = "../time" }
trogging = { path = "../trogging", default-features = false, features = ["clap"] }
write_buffer = { path = "../write_buffer" }


clap = { version = "3", features = ["derive", "env"] }
futures = "0.3"
snafu = "0.7"
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
tempfile = "3.1.0"
