---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: debug
          image: nixery.dev/shell/findutils/gnugrep/gnutar/hexdump/less/mount/procps/curl/grpcurl/binutils/gdb/strace/rustc/linuxpackages.perf/perf-tools/gzip/zstd
          command:
            - /bin/bash
            - -c
            - --
          args:
            - while true; do sleep 30; done;
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 2G
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      shareProcessNamespace: true
