---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iox-router-configs
data:
  router-1: |
    {
      "router": {
          "name": "myorg_mybucket",
          "write_sharder": {
              "specific_targets": [
                  {
                      "matcher": {
                          "table_name_regex": ".*"
                      },
                      "shard": 1
                  }
              ],
              "hash_ring": null
          },
          "write_sinks": {
              "1": {
                  "sinks": [
                      {
                          "write_buffer": {
                              "direction": "DIRECTION_WRITE",
                              "type": "kafka",
                              "connection": "redpanda-service:9093",
                              "connection_config": {},
                              "creation_config": {
                                  "n_sequencers": 1,
                                  "options": {}
                              }
                          },
                          "ignore_errors": false
                      }
                  ]
              }
          },
          "query_sinks": null
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iox-query-configs
data:
  database-1: |
    {
        "rules": {
            "name": "myorg_mybucket",
            "partition_template": {
                "parts": [
                    {"time": "%Y-%m-%d %H:00:00"}
                ]
            },
            "lifecycle_rules": {
                "buffer_size_soft": 1073741824,
                "buffer_size_hard": 2147483648,
                "worker_backoff_millis": 100,
                "max_active_compactions": 1,
                "persist": true,
                "persist_row_threshold": 10000000,
                "catalog_transactions_until_checkpoint": 100,
                "late_arrive_window_seconds": 300,
                "persist_age_threshold_seconds": 1800,
                "mub_row_threshold": 100000
            },
            "routing_config": {"sink": {"kafka": {}}},
            "worker_cleanup_avg_sleep": "500s",
            "write_buffer_connection": {
                "direction": "DIRECTION_READ",
                "type": "kafka",
                "connection": "redpanda-service:9093",
                "connection_config": {},
                "creation_config": {
                    "n_sequencers": 1,
                    "options": {}
                }
            }
        }
    }
