---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: iox
          image: quay.io/influxdb/iox:main
          imagePullPolicy: Always
        - name: glue
          image: europe-west3-docker.pkg.dev/influxdata-fusion/mneumann-repository-docker-1/iox-glue
          imagePullPolicy: Always
