---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: iox-query-configs
    files:
      - database-1.json
    options:
      # we don't wanna recreate containers when configs change
      disableNameSuffixHash: true
  - name: iox-router-configs
    files:
      - router-1.json
    options:
      # we don't wanna recreate containers when configs change
      disableNameSuffixHash: true
