[package]
name = "server_util"
description = "Shared code for IOx servers"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
http = "0.2.9"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

